export const CONFLICT_REASON = {
  EXACT_DUPLICATE: "exact_duplicate",
  SEMANTIC_DRIFT: "semantic_drift_irrelevant",
  SEARCH_INTENT_MISMATCH: "search_intent_mismatch",
  CATEGORY_CONFLICT: "category_conflict",
  SEMANTIC_DUPLICATE: "semantic_duplicate",
  EXISTING_URL_CANNIBALIZATION: "existing_url_cannibalization",
  BRAND_CONFLICT: "brand_conflict",
  LOW_SPECIFICITY: "low_specificity_generic",
  SCENE_CONTEXT_ONLY: "scene_context_only",
} as const;

export type ConflictReasonCode = (typeof CONFLICT_REASON)[keyof typeof CONFLICT_REASON];

export const REASON_PRECEDENCE: readonly ConflictReasonCode[] = [
  CONFLICT_REASON.EXACT_DUPLICATE,
  CONFLICT_REASON.BRAND_CONFLICT,
  CONFLICT_REASON.EXISTING_URL_CANNIBALIZATION,
  CONFLICT_REASON.CATEGORY_CONFLICT,
  CONFLICT_REASON.SEARCH_INTENT_MISMATCH,
  CONFLICT_REASON.SEMANTIC_DRIFT,
  CONFLICT_REASON.SEMANTIC_DUPLICATE,
  CONFLICT_REASON.LOW_SPECIFICITY,
  CONFLICT_REASON.SCENE_CONTEXT_ONLY,
] as const;

export const REASON_PRECEDENCE_RANK: Readonly<Record<ConflictReasonCode, number>> = {
  [CONFLICT_REASON.EXACT_DUPLICATE]: 1,
  [CONFLICT_REASON.BRAND_CONFLICT]: 2,
  [CONFLICT_REASON.EXISTING_URL_CANNIBALIZATION]: 3,
  [CONFLICT_REASON.CATEGORY_CONFLICT]: 4,
  [CONFLICT_REASON.SEARCH_INTENT_MISMATCH]: 5,
  [CONFLICT_REASON.SEMANTIC_DRIFT]: 6,
  [CONFLICT_REASON.SEMANTIC_DUPLICATE]: 7,
  [CONFLICT_REASON.LOW_SPECIFICITY]: 8,
  [CONFLICT_REASON.SCENE_CONTEXT_ONLY]: 9,
};
