/** Schema for the Auto SEO backup repository. Production migration orchestration is owned by infrastructure. */
export function getAutoSeoPostgresSchemaSql(schema: string): string {
  return `
    CREATE SCHEMA IF NOT EXISTS ${schema};
    CREATE TABLE IF NOT EXISTS ${schema}.auto_seo_product_backups (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      backup_id TEXT NOT NULL UNIQUE,
      workflow_id TEXT NOT NULL,
      store_id TEXT NOT NULL,
      shop_domain TEXT NOT NULL,
      product_id TEXT NOT NULL,
      product_handle TEXT NOT NULL,
      product_title TEXT NOT NULL,
      shopify_updated_at TEXT,
      snapshot_json TEXT NOT NULL,
      snapshot_sha256 TEXT NOT NULL,
      seo_input_sha256 TEXT,
      downstream_status TEXT NOT NULL CHECK (downstream_status IN ('NOT_SENT', 'SENT', 'FAILED')),
      downstream_http_status INTEGER,
      downstream_error TEXT,
      downstream_sent_at TEXT,
      created_at TEXT NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
      gpt_settings_json TEXT,
      CONSTRAINT uq_auto_seo_workflow_store_product UNIQUE (workflow_id, store_id, product_id)
    );
    CREATE INDEX IF NOT EXISTS idx_auto_seo_store_product
      ON ${schema}.auto_seo_product_backups(store_id, product_id);
    CREATE INDEX IF NOT EXISTS idx_auto_seo_created_at
      ON ${schema}.auto_seo_product_backups(created_at);
    ALTER TABLE ${schema}.auto_seo_product_backups
      ADD COLUMN IF NOT EXISTS seo_input_sha256 TEXT;
    CREATE INDEX IF NOT EXISTS idx_auto_seo_store_product_input
      ON ${schema}.auto_seo_product_backups(store_id, product_id, seo_input_sha256, downstream_status);
  `;
}
