import type { AmazonCrawlerReviewItem } from "../../modules/amazon-crawler";
import type { CrawlProduct } from "../../modules/customization-normalizer";
import type { PodDeliverableItem } from "../../modules/pinterest-pod";
import type {
  AutoSeoItemResult,
  CustomizationSeoItemResult,
  PinterestPodSeoItemResult,
  SeoContentImageOutput,
  SeoContentOutput,
} from "../../modules/seo-content";
import { seoContentMockData } from "../../modules/seo-content";
import type {
  ApprovedProductPatch,
  ApprovedProductUpdate,
} from "../../modules/orchestrator";
import type {
  DisplayField,
  FieldSource,
  ReviewDecision,
  SeoImageUiViewModel,
  SeoProcessingStatus,
  SeoProductBackup,
  SeoProductUiViewModel,
  ShopifySyncStatus,
} from "./types";

/**
 * Standard utility to tag a value with provenance ("real" or "mock").
 *
 * If `realValue` is defined, non-null, and non-empty (for strings/arrays),
 * returns `{ value: realValue, source: "real" }`.
 * Otherwise, returns `{ value: fallbackValue, source: "mock" }`.
 */
export function getDisplayValue<T>(
  realValue: T | null | undefined,
  fallbackValue: T,
): DisplayField<T> {
  if (realValue === null || realValue === undefined) {
    return { value: fallbackValue, source: "mock" };
  }

  if (typeof realValue === "string") {
    const trimmed = realValue.trim();
    if (trimmed.length > 0) {
      return { value: realValue as T, source: "real" };
    }
    return { value: fallbackValue, source: "mock" };
  }

  if (Array.isArray(realValue)) {
    if (realValue.length > 0) {
      return { value: realValue, source: "real" };
    }
    return { value: fallbackValue, source: "mock" };
  }

  return { value: realValue, source: "real" };
}

export interface AdaptSeoOutputOptions {
  readonly id?: string;
  readonly storeId?: string;
  readonly productId?: string;
  readonly asin?: string;
  readonly niche?: string;
  readonly defaultStatus?: SeoProcessingStatus;
  readonly initialDecision?: ReviewDecision;
  readonly isStatusReal?: boolean;
  readonly sourceCrawlProduct?: CrawlProduct;
  readonly shopifySyncStatus?: ShopifySyncStatus;
  readonly shopifyAdminUrl?: string;
  readonly originalBackup?: SeoProductBackup;
}

/**
 * Maps a single image output into SeoImageUiViewModel with field provenance.
 */
export function adaptImageToViewModel(
  image: SeoContentImageOutput | undefined,
  index: number,
  fallbackHandle: string,
): SeoImageUiViewModel {
  const fallbackIndex = index + 1;
  const safeHandle = fallbackHandle.trim() || "product";

  const previewField = getDisplayValue(
    image?.sourceUrl,
    "https://placehold.co/600x600/1e293b/94a3b8?text=Image+Preview",
  );

  const altField = getDisplayValue(
    image?.alt,
    `Product image ${fallbackIndex} for ${safeHandle}`,
  );

  const webpUrlField = getDisplayValue(
    image?.webp?.url,
    `/api/assets/${safeHandle}-${fallbackIndex}.webp`,
  );

  const webpFilenameField = getDisplayValue(
    image?.webp?.filename,
    `${safeHandle}-${fallbackIndex}.webp`,
  );

  return {
    id: `img-${index}-${Date.now()}`,
    previewUrl: previewField,
    alt: altField,
    webpUrl: webpUrlField,
    webpFilename: webpFilenameField,
  };
}

/**
 * Core adapter mapping SeoContentOutput into SeoProductUiViewModel.
 *
 * Checks field existence and tracks source ("real" vs "mock") per field.
 */
export function adaptSeoOutputToViewModel(
  output: Partial<SeoContentOutput> | null | undefined,
  options: AdaptSeoOutputOptions = {},
): SeoProductUiViewModel {
  const safeId = options.id || options.productId || `prod-seo-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
  const fallbackHandle = (output?.productHandle || options.asin || "custom-product")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  const productTitleField = getDisplayValue(
    output?.productTitle,
    options.asin ? `Product ${options.asin} (Pending SEO Content)` : "Product Title (Pending SEO Generation)",
  );

  const productDescriptionField = getDisplayValue(
    output?.productDescription,
    "<p>Detailed product description has not yet been generated by the SEO Content module.</p>",
  );

  const seoTitleField = getDisplayValue(
    output?.productSeoTitle,
    productTitleField.value.length > 70 ? productTitleField.value.slice(0, 67) + "..." : productTitleField.value,
  );

  const seoDescriptionField = getDisplayValue(
    output?.productSeoDescription,
    "Discover high-quality custom merchandise tailored to your personal aesthetic and living spaces. Order online with premium materials.",
  );

  const handleField = getDisplayValue(
    output?.productHandle,
    fallbackHandle || "custom-product",
  );

  // Images mapping
  const rawImages = output?.images && Array.isArray(output.images) ? output.images : [];
  let images: readonly SeoImageUiViewModel[];

  if (rawImages.length > 0) {
    images = rawImages.map((img, idx) => adaptImageToViewModel(img, idx, handleField.value));
  } else {
    // Generate at least one fallback image entry so the UI has structure
    images = [adaptImageToViewModel(undefined, 0, handleField.value)];
  }

  // SEO Status: if explicitly specified as real in options, mark as real; otherwise check if completed
  const determinedStatus: SeoProcessingStatus = options.defaultStatus || (output?.productTitle ? "completed" : "processing");
  const seoStatusField: DisplayField<SeoProcessingStatus> = {
    value: determinedStatus,
    source: options.isStatusReal ? "real" : "mock",
  };

  return {
    id: safeId,
    storeId: options.storeId,
    productId: options.productId,
    asin: options.asin,
    sourceNiche: options.niche,
    productTitle: productTitleField,
    productDescription: productDescriptionField,
    seoTitle: seoTitleField,
    seoDescription: seoDescriptionField,
    handle: handleField,
    images,
    seoStatus: seoStatusField,
    reviewDecision: options.initialDecision || "pending",
    updatedAt: Date.now(),
    sourceCrawlProduct: options.sourceCrawlProduct,
    shopifySyncStatus: options.shopifySyncStatus || "idle",
    shopifyAdminUrl: options.shopifyAdminUrl,
    originalBackup: options.originalBackup,
  };
}

/**
 * Adapts CustomizationSeoItemResult (from customization-adapter) to SeoProductUiViewModel.
 */
export function adaptCustomizationItemToViewModel(
  item: CustomizationSeoItemResult,
  fallbackStoreId?: string,
): SeoProductUiViewModel {
  const sourceProduct = item.sourceProduct as {
    storeId?: string;
    pipeline?: { shopify?: { storeId?: string; productId?: string; adminUrl?: string } };
    shopify?: { storeId?: string; productId?: string; adminUrl?: string };
    sourceDescriptionHtml?: string;
    descriptionHtml?: string;
    seo?: { title?: string; description?: string };
    seoTitle?: string;
    seoDescription?: string;
    sourceKey?: string;
  };

  const crawlShopify = sourceProduct.pipeline?.shopify || sourceProduct.shopify;
  const existingShopifyId = crawlShopify?.productId;
  const effectiveProductId = existingShopifyId || item.productId;

  const storeId =
    sourceProduct.storeId ||
    crawlShopify?.storeId ||
    fallbackStoreId;

  const rawTitle = (item.sourceProduct.title || item.sourceProduct.sourceTitle || item.seoInput?.title || "").trim();
  const rawDesc = (
    sourceProduct.sourceDescriptionHtml ||
    sourceProduct.descriptionHtml ||
    item.sourceProduct.description ||
    item.seoInput?.description ||
    ""
  ).trim();
  const rawHandle = (typeof item.sourceProduct.handle === "string" ? item.sourceProduct.handle.trim() : undefined) || item.seoInput?.handle || undefined;

  const originalSeo = sourceProduct.seo;
  const directSeoTitle = sourceProduct.seoTitle;
  const directSeoDescription = sourceProduct.seoDescription;

  const customSeoTitle = typeof directSeoTitle === "string" && directSeoTitle.trim().length > 0
    ? directSeoTitle.trim()
    : typeof originalSeo?.title === "string" && originalSeo.title.trim().length > 0
      ? originalSeo.title.trim()
      : undefined;

  const customSeoDescription = typeof directSeoDescription === "string" && directSeoDescription.trim().length > 0
    ? directSeoDescription.trim()
    : typeof originalSeo?.description === "string" && originalSeo.description.trim().length > 0
      ? originalSeo.description.trim()
      : undefined;

  const originalBackup: SeoProductBackup = {
    productTitle: rawTitle || "Custom Product",
    productDescription: rawDesc,
    handle: rawHandle,
    seoTitle: customSeoTitle,
    seoDescription: customSeoDescription,
    backedUpAt: Date.now(),
  };

  const splitValue =
    (item.sourceProduct.splitContext && typeof item.sourceProduct.splitContext.value === "string" ? item.sourceProduct.splitContext.value.trim() : undefined) ||
    (Array.isArray(item.sourceProduct.variants) && item.sourceProduct.variants[0] && typeof (item.sourceProduct.variants[0] as { options?: Record<string, unknown> }).options === "object"
      ? Object.values((item.sourceProduct.variants[0] as { options?: Record<string, unknown> }).options || {})
          .filter((v): v is string => typeof v === "string" && v.trim().length > 0)
          .join(" / ") || undefined
      : undefined) ||
    (typeof sourceProduct.sourceKey === "string" ? sourceProduct.sourceKey.split(":").at(-1)?.trim() : undefined);

  const baseAsin = item.sourceProduct.parentAsin || item.sourceProduct.asin || item.asin;
  const uniqueId =
    (typeof sourceProduct.sourceKey === "string" && sourceProduct.sourceKey.trim().length > 0 ? sourceProduct.sourceKey.trim() : undefined) ||
    (baseAsin && splitValue ? `${baseAsin}-${splitValue}` : undefined) ||
    (effectiveProductId && splitValue ? `${effectiveProductId}-${splitValue}` : effectiveProductId) ||
    (item.sourceProduct.id && !item.sourceProduct.id.startsWith("job-") ? item.sourceProduct.id : undefined) ||
    item.productId ||
    (splitValue ? `item-${splitValue}` : undefined) ||
    baseAsin ||
    `item-${Date.now()}`;

  const options: AdaptSeoOutputOptions = {
    id: uniqueId,
    storeId,
    productId: effectiveProductId,
    asin: baseAsin,
    niche: item.sourceProduct.categories?.[0] || "Custom Product",
    defaultStatus: item.success ? "completed" : "failed",
    isStatusReal: true,
    sourceCrawlProduct: item.sourceProduct,
    shopifyAdminUrl: crawlShopify?.adminUrl,
    shopifySyncStatus: crawlShopify?.productId ? "synced" : "idle",
    originalBackup,
  };


  if (!item.success) {
    return {
      ...adaptSeoOutputToViewModel(undefined, options),
      rejectionReason: item.error || "SEO Content processing failed",
    };
  }

  return adaptSeoOutputToViewModel(item.seoOutput, options);
}

export function adaptAmazonCrawlerReviewToViewModel(
  item: AmazonCrawlerReviewItem,
  resolveImageUrl: (fileToken: string) => string,
): SeoProductUiViewModel {
  const product = item.product;
  const images: readonly SeoImageUiViewModel[] = product.media
    .filter((media) => media.kind !== "video")
    .map((media, index) => {
      const processedFileToken = (media as unknown as { processedFileToken?: string }).processedFileToken;
      const previewUrl = processedFileToken ? resolveImageUrl(processedFileToken) : media.processedUrl || media.url;
      return {
        id: media.url || media.amazonImageId || `${item.id}-image-${index + 1}`,
        previewUrl: { value: previewUrl, source: "real" },
        alt: { value: media.alt || product.title, source: "real" },
        webpUrl: { value: previewUrl, source: "real" },
        webpFilename: { value: processedFileToken || "", source: "real" },
      };
    });
  const syncedProductId = product.pipeline?.shopify.productId;
  const updatedAt = item.updatedAt ? Date.parse(item.updatedAt) : Date.now();
  return {
    id: item.id,
    storeId: item.storeId || product.pipeline?.shopify.storeId,
    productId: syncedProductId,
    asin: product.parentAsin,
    sourceNiche: product.categories[0],
    coordinatorReview: {
      itemId: item.id,
      jobId: item.jobId,
      version: item.version,
      target: item.target,
    },
    productTitle: { value: product.title, source: "real" },
    productDescription: { value: product.descriptionHtml || product.description || "", source: "real" },
    seoTitle: { value: product.seo?.title || product.title, source: "real" },
    seoDescription: { value: product.seo?.description || "", source: "real" },
    handle: { value: product.handle || "", source: "real" },
    images,
    seoStatus: { value: "completed", source: "real" },
    reviewDecision: item.decision,
    rejectionReason: item.rejectionReason || undefined,
    updatedAt: Number.isFinite(updatedAt) ? updatedAt : Date.now(),
    sourceCrawlProduct: product as unknown as CrawlProduct,
    shopifySyncStatus: item.syncStatus,
    shopifyAdminUrl: product.pipeline?.shopify.adminUrl,
    shopifySyncError: item.syncError || undefined,
    shopifySyncedAt: item.syncStatus === "synced" ? updatedAt : undefined,
    isSyncing: item.syncStatus === "queued" || item.syncStatus === "syncing",
    syncError: item.syncError || undefined,
    lastSyncedAt: item.syncStatus === "synced" ? updatedAt : undefined,
  };
}

/**
 * Adapts AutoSeoItemResult (from auto-seo-adapter) to SeoProductUiViewModel.
 */
export function adaptAutoSeoItemToViewModel(
  item: AutoSeoItemResult,
  fallbackStoreId?: string,
): SeoProductUiViewModel {
  const sourceProduct = item.sourceProduct;
  const storeId =
    (sourceProduct as { storeId?: string })?.storeId ||
    item.storeId ||
    fallbackStoreId;
  const firstTag = Array.isArray(sourceProduct.tags) && typeof sourceProduct.tags[0] === "string"
    ? sourceProduct.tags[0]
    : undefined;
  const niche = firstTag || sourceProduct.productType || "Shopify Product";

  const rawTitle = typeof sourceProduct.sourceTitle === "string" && sourceProduct.sourceTitle.trim().length > 0
    ? sourceProduct.sourceTitle
    : typeof sourceProduct.title === "string" && sourceProduct.title.trim().length > 0
      ? sourceProduct.title
      : item.seoInput?.title || "";

  let rawDesc = "";
  if (typeof sourceProduct.sourceDescriptionHtml === "string" && sourceProduct.sourceDescriptionHtml.trim().length > 0) {
    rawDesc = sourceProduct.sourceDescriptionHtml.trim();
  } else if (typeof sourceProduct.descriptionHtml === "string" && sourceProduct.descriptionHtml.trim().length > 0) {
    rawDesc = sourceProduct.descriptionHtml.trim();
  } else if (typeof sourceProduct.description === "string" && sourceProduct.description.trim().length > 0) {
    rawDesc = sourceProduct.description.trim();
  } else if (typeof item.seoInput?.description === "string") {
    rawDesc = item.seoInput.description.trim();
  }

  const rawHandle = typeof sourceProduct.handle === "string" && sourceProduct.handle.trim().length > 0
    ? sourceProduct.handle.trim()
    : item.handle || item.seoInput?.handle || undefined;

  const originalSeo = (sourceProduct as { seo?: { title?: string; description?: string } })?.seo;
  const directSeoTitle = (sourceProduct as { seoTitle?: string })?.seoTitle;
  const directSeoDescription = (sourceProduct as { seoDescription?: string })?.seoDescription;
  const sourceSeoTitle = (sourceProduct as { sourceSeoTitle?: string })?.sourceSeoTitle;
  const sourceSeoDescription = (sourceProduct as { sourceSeoDescription?: string })?.sourceSeoDescription;

  const rawSeoTitle = typeof directSeoTitle === "string" && directSeoTitle.trim().length > 0
    ? directSeoTitle.trim()
    : typeof sourceSeoTitle === "string" && sourceSeoTitle.trim().length > 0
      ? sourceSeoTitle.trim()
      : typeof originalSeo?.title === "string" && originalSeo.title.trim().length > 0
        ? originalSeo.title.trim()
        : undefined;

  const rawSeoDescription = typeof directSeoDescription === "string" && directSeoDescription.trim().length > 0
    ? directSeoDescription.trim()
    : typeof sourceSeoDescription === "string" && sourceSeoDescription.trim().length > 0
      ? sourceSeoDescription.trim()
      : typeof originalSeo?.description === "string" && originalSeo.description.trim().length > 0
        ? originalSeo.description.trim()
        : undefined;

  const originalBackup: SeoProductBackup = {
    productTitle: rawTitle.trim() || "Untitled Product",
    productDescription: rawDesc.trim(),
    handle: rawHandle,
    seoTitle: rawSeoTitle,
    seoDescription: rawSeoDescription,
    backedUpAt: Date.now(),
  };

  const options: AdaptSeoOutputOptions = {
    id: item.productId || `item-${Date.now()}`,
    storeId,
    productId: item.productId,
    niche,
    defaultStatus: item.success ? "completed" : "failed",
    isStatusReal: true,
    originalBackup,
  };

  if (!item.success) {
    return {
      ...adaptSeoOutputToViewModel(undefined, options),
      rejectionReason: item.error || "SEO Content processing failed",
    };
  }

  return adaptSeoOutputToViewModel(item.seoOutput, options);
}

/**
 * Adapts PinterestPodSeoItemResult (from pinterest-pod-adapter) to SeoProductUiViewModel.
 */
export function adaptPinterestPodItemToViewModel(
  item: PinterestPodSeoItemResult,
): SeoProductUiViewModel {
  const podItem = (item.sourceItem ?? item.deliverableItem) as unknown as PodDeliverableItem;
  const niche = podItem?.trendKeywords && podItem.trendKeywords.length > 0
    ? podItem.trendKeywords[0]
    : podItem?.productType || "POD";

  const options: AdaptSeoOutputOptions = {
    id: item.designId || `pod-${Date.now()}`,
    productId: item.designId,
    niche,
    defaultStatus: item.success ? "completed" : "failed",
    isStatusReal: true,
  };

  if (!item.success) {
    return {
      ...adaptSeoOutputToViewModel(undefined, options),
      sourcePinterestItem: podItem,
      rejectionReason: item.error || "SEO Content processing failed for Pinterest POD item",
    };
  }

  const baseViewModel = adaptSeoOutputToViewModel(item.seoOutput, options);
  return {
    ...baseViewModel,
    sourcePinterestItem: podItem,
  };
}

/**
 * Returns a rich set of initial sample view models for UI testing & review.
 * Demonstrates:
 * 1. Fully authentic SEO item (all "real")
 * 2. Partial item with some missing fields (shows subtle [Mock] tags)
 * 3. Item currently processing
 * 4. Item that failed SEO generation
 */
export function getInitialSampleViewModels(): readonly SeoProductUiViewModel[] {
  // 1. Fully populated from seoContentMockData (Real)
  const item1 = adaptSeoOutputToViewModel(seoContentMockData, {
    id: "sample-prod-101",
    storeId: "store-us-primary",
    productId: "gid://shopify/Product/98412351",
    asin: "B09MUSIC01",
    niche: "Vintage Rugs",
    defaultStatus: "completed",
    isStatusReal: true,
    originalBackup: {
      productTitle: "Vintage Oriental Area Rug 5x7 Living Room Carpet",
      productDescription: "<p>Original rug description before AI SEO rewrite.</p>",
      handle: "vintage-oriental-area-rug-5x7",
      seoTitle: "Vintage Oriental Area Rug 5x7",
      seoDescription: "Original vintage oriental area rug 5x7 living room carpet.",
      backedUpAt: Date.now(),
    },
  });

  // 2. Partial Item: missing SEO Description & WebP URLs (Mock fallback tagged)
  const partialOutput: Partial<SeoContentOutput> = {
    productTitle: "Gothic Coffin Bookcase Miniature, Wooden Spooky Shelf",
    productDescription: "<p>Handcrafted wooden miniature coffin bookcase with velvet lined interior for crystals, curios, and small oddities.</p>",
    productSeoTitle: "Gothic Coffin Bookcase Miniature | Spooky Curio Shelf",
    productHandle: "gothic-coffin-bookcase-miniature",
    images: [
      {
        sourceUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
        alt: "Gothic coffin shaped miniature wooden bookshelf on display table",
        webp: {
          filename: "gothic-coffin-shelf.webp",
          // url intentionally omitted to demonstrate mock webp fallback
        },
      },
    ],
  };

  const item2 = adaptSeoOutputToViewModel(partialOutput, {
    id: "sample-prod-102",
    storeId: "store-us-primary",
    productId: "gid://shopify/Product/98412352",
    asin: "B08COFFIN2",
    niche: "Gothic Home Décor",
    defaultStatus: "completed",
    isStatusReal: true,
    originalBackup: {
      productTitle: "Mini Coffin Shelf Black Wood",
      productDescription: "<p>Small wooden gothic coffin shelf for crystals and curios.</p>",
      handle: "mini-coffin-shelf-black-wood",
      seoTitle: "Mini Coffin Shelf Black Wood",
      seoDescription: "Original miniature black wood coffin shelf for curio collection.",
      backedUpAt: Date.now(),
    },
  });

  // 3. Item currently Processing
  const item3 = adaptSeoOutputToViewModel(
    {
      productTitle: "Embroidered Celestial Star Velvet Cushion",
      productHandle: "embroidered-celestial-star-cushion",
    },
    {
      id: "sample-prod-103",
      storeId: "store-us-primary",
      productId: "gid://shopify/Product/98412353",
      asin: "B07STARMAG",
      niche: "Pillows & Cushions",
      defaultStatus: "processing",
      isStatusReal: true,
      originalBackup: {
        productTitle: "Celestial Star Velvet Pillow Blue",
        productDescription: "<p>Midnight navy velvet star shaped decorative cushion.</p>",
        handle: "celestial-star-velvet-pillow-blue",
        backedUpAt: Date.now(),
      },
    },
  );

  // 4. Item that Failed SEO generation
  const item4: SeoProductUiViewModel = {
    ...adaptSeoOutputToViewModel(undefined, {
      id: "sample-prod-104",
      storeId: "store-us-primary",
      productId: "gid://shopify/Product/98412354",
      asin: "B01FAIL004",
      niche: "Apparel",
      defaultStatus: "failed",
      isStatusReal: true,
      initialDecision: "rejected",
      originalBackup: {
        productTitle: "Graphic Cotton T-Shirt Unisex",
        productDescription: "<p>Original retro print t-shirt.</p>",
        handle: "graphic-cotton-t-shirt-unisex",
        backedUpAt: Date.now(),
      },
    }),
    rejectionReason: "Vision API quota exhausted on 3 image inputs. Retry needed.",
  };

  return [item1, item2, item3, item4];
}

/**
 * Maps a single SeoProductUiViewModel to the ApprovedProductUpdate structure
 * expected by applyApprovedProductUpdates in orchestrator.
 */
export function adaptViewModelToApprovedUpdate(
  viewModel: SeoProductUiViewModel,
): ApprovedProductUpdate {
  const rawId = viewModel.productId || viewModel.id;
  const productId = rawId.trim();

  const patch: ApprovedProductPatch = {};

  const title = viewModel.productTitle?.value?.trim();
  if (title) {
    (patch as Record<string, unknown>).title = title;
  }

  const descriptionHtml = viewModel.productDescription?.value?.trim();
  if (descriptionHtml) {
    (patch as Record<string, unknown>).descriptionHtml = descriptionHtml;
  }

  const handle = viewModel.handle?.value?.trim();
  if (handle) {
    (patch as Record<string, unknown>).handle = handle;
  }

  const seoTitle = viewModel.seoTitle?.value?.trim();
  const seoDescription = viewModel.seoDescription?.value?.trim();
  if (seoTitle || seoDescription) {
    const seoObj: Record<string, string> = {};
    if (seoTitle) {
      seoObj.title = seoTitle;
    }
    if (seoDescription) {
      seoObj.description = seoDescription;
    }
    (patch as Record<string, unknown>).seo = seoObj;
  }

  return {
    productId,
    patch,
  };
}

/**
 * Maps multiple SeoProductUiViewModel items to ApprovedProductUpdate array.
 */
export function adaptViewModelsToApprovedUpdates(
  viewModels: readonly SeoProductUiViewModel[],
): readonly ApprovedProductUpdate[] {
  return viewModels.map(adaptViewModelToApprovedUpdate);
}

/**
 * Maps a single SeoProductUiViewModel to the rollback ApprovedProductUpdate structure
 * using its backed-up original product data.
 */
export function adaptViewModelToRollbackUpdate(
  viewModel: SeoProductUiViewModel,
): ApprovedProductUpdate | null {
  const backup = viewModel.originalBackup;
  if (!backup) {
    return null;
  }

  const rawId = viewModel.productId || viewModel.id;
  const productId = rawId.trim();
  if (!productId) {
    return null;
  }

  const patch: ApprovedProductPatch = {};

  const title = backup.productTitle?.trim();
  if (title) {
    (patch as Record<string, unknown>).title = title;
  }

  if (backup.productDescription !== undefined) {
    (patch as Record<string, unknown>).descriptionHtml = backup.productDescription.trim();
  }

  const handle = backup.handle?.trim();
  if (handle) {
    (patch as Record<string, unknown>).handle = handle;
  }

  // Restore SEO: if original had explicit custom seoTitle / seoDescription, restore them;
  // otherwise revert seoTitle to original product title and seoDescription to empty string
  // so Shopify clears any AI SEO overrides applied during approval.
  const seoTitle = backup.seoTitle !== undefined && backup.seoTitle.trim().length > 0
    ? backup.seoTitle.trim()
    : title || undefined;

  const seoDescription = backup.seoDescription !== undefined
    ? backup.seoDescription.trim()
    : "";

  const seoObj: Record<string, string> = {};
  if (seoTitle !== undefined) {
    seoObj.title = seoTitle;
  }
  seoObj.description = seoDescription;
  (patch as Record<string, unknown>).seo = seoObj;

  return {
    productId,
    patch,
  };
}

/**
 * Maps multiple SeoProductUiViewModel items to rollback ApprovedProductUpdate array.
 */
export function adaptViewModelsToRollbackUpdates(
  viewModels: readonly SeoProductUiViewModel[],
): readonly ApprovedProductUpdate[] {
  const updates: ApprovedProductUpdate[] = [];
  for (const vm of viewModels) {
    const update = adaptViewModelToRollbackUpdate(vm);
    if (update) {
      updates.push(update);
    }
  }
  return updates;
}
