import type {
  CustomizationSeoItemResult,
  SeoContentImageOutput,
  SeoContentOutput,
} from "../../modules/seo-content";
import { seoContentMockData } from "../../modules/seo-content";
import type {
  DisplayField,
  FieldSource,
  ReviewDecision,
  SeoImageUiViewModel,
  SeoProcessingStatus,
  SeoProductUiViewModel,
} from "./types";

/**
 * Standard utility to tag a value with provenance ("real" or "mock").
 *
 * If `realValue` is defined, non-null, and non-empty (for strings/arrays),
 * returns `{ value: realValue, source: "real" }`.
 * Otherwise, returns `{ value: fallbackValue, source: "mock" }`.
 */
export function getDisplayValue<T>(
  realValue: T | null | undefined,
  fallbackValue: T,
): DisplayField<T> {
  if (realValue === null || realValue === undefined) {
    return { value: fallbackValue, source: "mock" };
  }

  if (typeof realValue === "string") {
    const trimmed = realValue.trim();
    if (trimmed.length > 0) {
      return { value: realValue as T, source: "real" };
    }
    return { value: fallbackValue, source: "mock" };
  }

  if (Array.isArray(realValue)) {
    if (realValue.length > 0) {
      return { value: realValue, source: "real" };
    }
    return { value: fallbackValue, source: "mock" };
  }

  return { value: realValue, source: "real" };
}

export interface AdaptSeoOutputOptions {
  readonly id?: string;
  readonly productId?: string;
  readonly asin?: string;
  readonly niche?: string;
  readonly defaultStatus?: SeoProcessingStatus;
  readonly initialDecision?: ReviewDecision;
  readonly isStatusReal?: boolean;
}

/**
 * Maps a single image output into SeoImageUiViewModel with field provenance.
 */
export function adaptImageToViewModel(
  image: SeoContentImageOutput | undefined,
  index: number,
  fallbackHandle: string,
): SeoImageUiViewModel {
  const fallbackIndex = index + 1;
  const safeHandle = fallbackHandle.trim() || "product";

  const previewField = getDisplayValue(
    image?.sourceUrl,
    "https://placehold.co/600x600/1e293b/94a3b8?text=Image+Preview",
  );

  const altField = getDisplayValue(
    image?.alt,
    `Product image ${fallbackIndex} for ${safeHandle}`,
  );

  const webpUrlField = getDisplayValue(
    image?.webp?.url,
    `/api/assets/${safeHandle}-${fallbackIndex}.webp`,
  );

  const webpFilenameField = getDisplayValue(
    image?.webp?.filename,
    `${safeHandle}-${fallbackIndex}.webp`,
  );

  return {
    id: `img-${index}-${Date.now()}`,
    previewUrl: previewField,
    alt: altField,
    webpUrl: webpUrlField,
    webpFilename: webpFilenameField,
  };
}

/**
 * Core adapter mapping SeoContentOutput into SeoProductUiViewModel.
 *
 * Checks field existence and tracks source ("real" vs "mock") per field.
 */
export function adaptSeoOutputToViewModel(
  output: Partial<SeoContentOutput> | null | undefined,
  options: AdaptSeoOutputOptions = {},
): SeoProductUiViewModel {
  const safeId = options.id || options.productId || `prod-seo-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
  const fallbackHandle = (output?.productHandle || options.asin || "custom-product")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  const productTitleField = getDisplayValue(
    output?.productTitle,
    options.asin ? `Product ${options.asin} (Pending SEO Content)` : "Product Title (Pending SEO Generation)",
  );

  const productDescriptionField = getDisplayValue(
    output?.productDescription,
    "<p>Detailed product description has not yet been generated by the SEO Content module.</p>",
  );

  const seoTitleField = getDisplayValue(
    output?.productSeoTitle,
    productTitleField.value.length > 70 ? productTitleField.value.slice(0, 67) + "..." : productTitleField.value,
  );

  const seoDescriptionField = getDisplayValue(
    output?.productSeoDescription,
    "Discover high-quality custom merchandise tailored to your personal aesthetic and living spaces. Order online with premium materials.",
  );

  const handleField = getDisplayValue(
    output?.productHandle,
    fallbackHandle || "custom-product",
  );

  // Images mapping
  const rawImages = output?.images && Array.isArray(output.images) ? output.images : [];
  let images: readonly SeoImageUiViewModel[];

  if (rawImages.length > 0) {
    images = rawImages.map((img, idx) => adaptImageToViewModel(img, idx, handleField.value));
  } else {
    // Generate at least one fallback image entry so the UI has structure
    images = [adaptImageToViewModel(undefined, 0, handleField.value)];
  }

  // SEO Status: if explicitly specified as real in options, mark as real; otherwise check if completed
  const determinedStatus: SeoProcessingStatus = options.defaultStatus || (output?.productTitle ? "completed" : "processing");
  const seoStatusField: DisplayField<SeoProcessingStatus> = {
    value: determinedStatus,
    source: options.isStatusReal ? "real" : "mock",
  };

  return {
    id: safeId,
    productId: options.productId,
    asin: options.asin,
    sourceNiche: options.niche,
    productTitle: productTitleField,
    productDescription: productDescriptionField,
    seoTitle: seoTitleField,
    seoDescription: seoDescriptionField,
    handle: handleField,
    images,
    seoStatus: seoStatusField,
    reviewDecision: options.initialDecision || "pending",
    updatedAt: Date.now(),
  };
}

/**
 * Adapts CustomizationSeoItemResult (from customization-adapter) to SeoProductUiViewModel.
 */
export function adaptCustomizationItemToViewModel(
  item: CustomizationSeoItemResult,
): SeoProductUiViewModel {
  const options: AdaptSeoOutputOptions = {
    id: item.productId || item.asin || `item-${Date.now()}`,
    productId: item.productId,
    asin: item.asin,
    niche: item.sourceProduct.categories?.[0] || "Custom Product",
    defaultStatus: item.success ? "completed" : "failed",
    isStatusReal: true,
  };

  if (!item.success) {
    return {
      ...adaptSeoOutputToViewModel(undefined, options),
      rejectionReason: item.error || "SEO Content processing failed",
    };
  }

  return adaptSeoOutputToViewModel(item.seoOutput, options);
}

/**
 * Returns a rich set of initial sample view models for UI testing & review.
 * Demonstrates:
 * 1. Fully authentic SEO item (all "real")
 * 2. Partial item with some missing fields (shows subtle [Mock] tags)
 * 3. Item currently processing
 * 4. Item that failed SEO generation
 */
export function getInitialSampleViewModels(): readonly SeoProductUiViewModel[] {
  // 1. Fully populated from seoContentMockData (Real)
  const item1 = adaptSeoOutputToViewModel(seoContentMockData, {
    id: "sample-prod-101",
    productId: "gid://shopify/Product/98412351",
    asin: "B09MUSIC01",
    niche: "Vintage Rugs",
    defaultStatus: "completed",
    isStatusReal: true,
  });

  // 2. Partial Item: missing SEO Description & WebP URLs (Mock fallback tagged)
  const partialOutput: Partial<SeoContentOutput> = {
    productTitle: "Gothic Coffin Bookcase Miniature, Wooden Spooky Shelf",
    productDescription: "<p>Handcrafted wooden miniature coffin bookcase with velvet lined interior for crystals, curios, and small oddities.</p>",
    productSeoTitle: "Gothic Coffin Bookcase Miniature | Spooky Curio Shelf",
    productHandle: "gothic-coffin-bookcase-miniature",
    images: [
      {
        sourceUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
        alt: "Gothic coffin shaped miniature wooden bookshelf on display table",
        webp: {
          filename: "gothic-coffin-shelf.webp",
          // url intentionally omitted to demonstrate mock webp fallback
        },
      },
    ],
  };

  const item2 = adaptSeoOutputToViewModel(partialOutput, {
    id: "sample-prod-102",
    productId: "gid://shopify/Product/98412352",
    asin: "B08COFFIN2",
    niche: "Gothic Home Décor",
    defaultStatus: "completed",
    isStatusReal: true,
  });

  // 3. Item currently Processing
  const item3 = adaptSeoOutputToViewModel(
    {
      productTitle: "Embroidered Celestial Star Velvet Cushion",
      productHandle: "embroidered-celestial-star-cushion",
    },
    {
      id: "sample-prod-103",
      productId: "gid://shopify/Product/98412353",
      asin: "B07STARMAG",
      niche: "Pillows & Cushions",
      defaultStatus: "processing",
      isStatusReal: true,
    },
  );

  // 4. Item that Failed SEO generation
  const item4: SeoProductUiViewModel = {
    ...adaptSeoOutputToViewModel(undefined, {
      id: "sample-prod-104",
      productId: "gid://shopify/Product/98412354",
      asin: "B01FAIL004",
      niche: "Apparel",
      defaultStatus: "failed",
      isStatusReal: true,
      initialDecision: "rejected",
    }),
    rejectionReason: "Vision API quota exhausted on 3 image inputs. Retry needed.",
  };

  return [item1, item2, item3, item4];
}
