export { customizationNormalizerMockData } from "./mocks/data";
export { runMockCustomizationNormalizer } from "./mocks/runner";
export { getCustomizationNormalizerRunner } from "./runtime";
export {
  canonicalJsonStringify,
  cleanImageUrl,
  computeNormalizedProductChecksum,
  computeShortHash,
  extractFileExtension,
  fromPinterestPodItem,
  fromShopifyProduct,
  generateFriendlyFileName,
  hasCustomization,
  isSafeHttpUrl,
  normalizeCustomizationProduct,
  runCustomizationNormalizer,
  slugify,
  validateProductPayload,
} from "./service";
export type {
  CrawlJobSettings,
  CrawlJobStatistics,
  CrawlProduct,
  CustomizationAsset,
  CustomizationNormalizerInput,
  CustomizationNormalizerOutput,
  CustomizationOption,
  CustomizationOptionGroup,
  CustomizationOptionPrice,
  CustomizationPricing,
  CustomizationTextInput,
  ImageDimension,
  ImageResource,
  NormalizationSummary,
  PayloadValidationResult,
  PinterestPodDeliverableItemInput,
  ProductCustomization,
  ProductMediaItem,
  ShopifyProductInputForNormalization,
} from "./types";
