import { AsyncLocalStorage } from "node:async_hooks";
import { existsSync } from "node:fs";

import { Pool } from "pg";
import type { PoolClient } from "pg";

import { getSeoWorkerSchemaSql } from "../seo-worker/schema";
import { getSeoPublishSchemaSql } from "../seo-worker/publish-schema";
import { applySeoVersionMigrations } from "../seo-versioning";

export interface SeoQueuePostgresOptions {
  readonly databaseUrl: string;
  readonly schema?: string;
  /** Runtime guard only: never read or open the legacy database. */
  readonly legacySourcePath?: string;
}

export const QUEUE_TABLES = ["gpt_settings", "gpt_jobs", "gpt_batches", "gpt_mutations", "gpt_deliveries", "gpt_review_state", "gpt_sync", "gpt_audit"] as const;
export const QUEUE_LOCK = "ffp-seo-queue-v1";

export function getQueueSchemaSql(schema: string): string {
  if (!/^[a-z_][a-z0-9_]*$/.test(schema)) throw new Error("Invalid SEO queue schema");
  return `CREATE SCHEMA IF NOT EXISTS "${schema}";
    CREATE TABLE IF NOT EXISTS "${schema}".gpt_settings (store_id TEXT PRIMARY KEY, payload TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS "${schema}".gpt_jobs (id TEXT PRIMARY KEY, store_id TEXT NOT NULL, dedup TEXT NOT NULL, status TEXT NOT NULL, batch_id TEXT, payload TEXT NOT NULL, created_at BIGINT NOT NULL, provider TEXT NOT NULL DEFAULT 'custom_gpt', queue_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE, UNIQUE(store_id,dedup));
    CREATE INDEX IF NOT EXISTS gpt_provider_queue_idx ON "${schema}".gpt_jobs(store_id,provider,status,created_at,id);
    CREATE TABLE IF NOT EXISTS "${schema}".gpt_batches (id TEXT PRIMARY KEY, store_id TEXT NOT NULL, request_id TEXT NOT NULL, token TEXT NOT NULL, expires_at BIGINT NOT NULL, active INTEGER NOT NULL, provider TEXT NOT NULL DEFAULT 'custom_gpt', owner_id TEXT NOT NULL DEFAULT 'custom_gpt', queue_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE, UNIQUE(store_id,request_id));
    CREATE TABLE IF NOT EXISTS "${schema}".gpt_mutations (scope TEXT NOT NULL, request_id TEXT NOT NULL, digest TEXT NOT NULL, response TEXT, PRIMARY KEY(scope,request_id));
    CREATE TABLE IF NOT EXISTS "${schema}".gpt_deliveries (job_id TEXT PRIMARY KEY, payload TEXT NOT NULL, delivered INTEGER NOT NULL DEFAULT 0);
    CREATE TABLE IF NOT EXISTS "${schema}".gpt_review_state (job_id TEXT PRIMARY KEY, payload TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS "${schema}".gpt_review_archives (job_id TEXT PRIMARY KEY REFERENCES "${schema}".gpt_jobs(id), store_id TEXT NOT NULL, archived_at BIGINT NOT NULL);
    CREATE TABLE IF NOT EXISTS "${schema}".gpt_sync (job_id TEXT PRIMARY KEY, token TEXT NOT NULL, status TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS "${schema}".gpt_audit (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, store_id TEXT NOT NULL, job_id TEXT, event TEXT NOT NULL, created_at BIGINT NOT NULL);
    CREATE TABLE IF NOT EXISTS "${schema}".seo_queue_migrations (source_digest TEXT PRIMARY KEY, counts_json TEXT NOT NULL, completed_at TIMESTAMPTZ NOT NULL DEFAULT now());${getSeoWorkerSchemaSql(schema)}${getSeoPublishSchemaSql(schema)}`;
}

/** Fixed queue SQL only; all values remain bound parameters, never interpolated. */
export function translateQueueSql(sql: string, schema: string): string {
  if (!/^[a-z_][a-z0-9_]*$/.test(schema)) throw new Error("Invalid SEO queue schema");
  let parameter = 0;
  return sql
    .replace(/json_extract\(payload,'\$\.(\w+)'\)/g, (_expression, field: string) =>
      ["nextAttemptAt", "finalizerUntil"].includes(field)
        ? `(payload::jsonb->>'${field}')::bigint`
        : `(payload::jsonb->>'${field}')`)
    .replace(/\browid\b/g, "queue_order")
    .replace(/\bgpt_(settings|jobs|batches|mutations|deliveries|review_state|review_archives|sync|audit)\b/g, table => `"${schema}".${table}`)
    .replace(/\bseo_worker_(stores|tokens|sessions|runs|jobs|attempts|successes|requests|revisions|cutovers)\b/g, table => `"${schema}".${table}`)
    .replace(/\bseo_publish_(operations|versions)\b/g, table => `"${schema}".${table}`)
    .replace(/\?/g, () => `$${++parameter}`);
}

export class PostgresQueueDatabase {
  readonly pool: Pool;
  readonly schema: string;
  private readonly transactionContext = new AsyncLocalStorage<PoolClient>();
  private initialization: Promise<void> | undefined;
  private readonly legacySourcePath: string | undefined;

  constructor(options: SeoQueuePostgresOptions) {
    this.schema = options.schema ?? "public";
    this.legacySourcePath = options.legacySourcePath;
    getQueueSchemaSql(this.schema);
    const url = new URL(options.databaseUrl);
    if (!["postgres:", "postgresql:"].includes(url.protocol)) throw new Error("SEO queue requires a PostgreSQL database URL");
    this.pool = new Pool({ connectionString: options.databaseUrl, connectionTimeoutMillis: 10_000 });
  }

  initialize(): Promise<void> {
    return this.initialization ??= this.withTransaction(async client => {
      await client.query(getQueueSchemaSql(this.schema));
      await applySeoVersionMigrations({
        transaction: operation => operation({
          query: async (sql, values) => ({ rows: (await client.query<Record<string, unknown>>(sql, values)).rows }),
        }),
      }, this.schema);
      if (this.legacySourcePath && existsSync(this.legacySourcePath)) {
        const imported = await client.query(`SELECT 1 FROM "${this.schema}".seo_queue_migrations LIMIT 1`);
        if (!imported.rowCount) throw new Error("SEO_QUEUE_MIGRATION_REQUIRED: import the frozen SQLite queue before enabling PostgreSQL runtime");
      }
    });
  }

  private async withTransaction<T>(operation: (client: PoolClient) => Promise<T>): Promise<T> {
    const client = await this.pool.connect();
    try {
      await client.query("BEGIN");
      // Preserve the legacy single-writer invariants across every Gateway/MCP process.
      await client.query("SELECT pg_advisory_xact_lock(hashtext($1), hashtext($2))", [QUEUE_LOCK, this.schema]);
      const output = await operation(client);
      await client.query("COMMIT");
      return output;
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally { client.release(); }
  }

  async transaction<T>(operation: () => Promise<T>): Promise<T> {
    await this.initialize();
    if (this.transactionContext.getStore()) return operation();
    return this.withTransaction(client => this.transactionContext.run(client, operation));
  }

  async withClientTransaction<T>(operation: (client: PoolClient) => Promise<T>): Promise<T> {
    return this.transaction(async () => {
      const client = this.transactionContext.getStore();
      if (!client) throw new Error("SEO_QUEUE_TRANSACTION_REQUIRED");
      await client.query(`SET LOCAL search_path TO "${this.schema}"`);
      return operation(client);
    });
  }

  prepare(sql: string) {
    const query = async (parameters: readonly unknown[]) => {
      await this.initialize();
      const executor = this.transactionContext.getStore() ?? this.pool;
      try {
        return await executor.query<Record<string, unknown>>(translateQueueSql(sql, this.schema), [...parameters]);
      } catch (error) {
        throw new Error("SEO_QUEUE_STORAGE_UNAVAILABLE: PostgreSQL operation failed; retry after checking database health", { cause: error });
      }
    };
    return {
      get: async (...parameters: readonly unknown[]): Promise<Record<string, unknown> | undefined> => (await query(parameters)).rows[0],
      all: async (...parameters: readonly unknown[]): Promise<Record<string, unknown>[]> => (await query(parameters)).rows,
      run: async (...parameters: readonly unknown[]): Promise<{ changes: number }> => ({ changes: (await query(parameters)).rowCount ?? 0 }),
    };
  }

  async close(): Promise<void> { await this.pool.end(); }
}
